# Generated by Django 6.0.8 on 2026-08-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=16, verbose_name='平台')),
                ('author_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='平台侧ID')),
                ('name', models.CharField(max_length=128, verbose_name='作者名')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像地址')),
                ('follower_count', models.BigIntegerField(default=0, verbose_name='粉丝数')),
                ('profile_url', models.URLField(blank=True, null=True, verbose_name='主页地址')),
                ('is_key_author', models.BooleanField(default=False, verbose_name='重点账号')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'indexes': [models.Index(fields=['platform', 'name'], name='posts_autho_platfor_b40286_idx')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=128, verbose_name='平台帖子ID')),
                ('platform', models.CharField(max_length=16, verbose_name='平台')),
                ('url', models.URLField(unique=True, verbose_name='原始链接')),
                ('title', models.CharField(blank=True, default='', max_length=512, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='内容哈希')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='评论数')),
                ('share_count', models.BigIntegerField(default=0, verbose_name='转发数')),
                ('favorite_count', models.BigIntegerField(default=0, verbose_name='收藏数')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='话题标签')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='封面地址')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片/视频封面')),
                ('dedup_group', models.CharField(blank=True, max_length=64, null=True, verbose_name='相似去重组')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='软删除')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='PostKeywordHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128, verbose_name='关键词快照')),
                ('matched_text', models.CharField(max_length=128, verbose_name='命中原文片段')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_hits', to='posts.post', verbose_name='帖子')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '关键词命中明细',
                'verbose_name_plural': '关键词命中明细',
            },
        ),
        migrations.CreateModel(
            name='PostSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.BigIntegerField(default=0, verbose_name='评论数')),
                ('share_count', models.BigIntegerField(default=0, verbose_name='转发数')),
                ('favorite_count', models.BigIntegerField(default=0, verbose_name='收藏数')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '互动快照',
                'verbose_name_plural': '互动快照',
            },
        ),
        migrations.CreateModel(
            name='PostTopicHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_keywords', models.JSONField(blank=True, default=list, verbose_name='命中关键词')),
                ('matched_count', models.IntegerField(default=0, verbose_name='命中词数')),
                ('first_hit_at', models.DateTimeField(auto_now_add=True, verbose_name='首次命中时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_hits', to='posts.post', verbose_name='帖子')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hits', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '帖帖命中关联',
                'verbose_name_plural': '帖帖命中关联',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['platform', 'post_id'], name='posts_post_platfor_0bbdb7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['platform', 'published_at'], name='posts_post_platfor_62d0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['dedup_group'], name='posts_post_dedup_g_46a1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['collected_at'], name='posts_post_collect_05fbe6_idx'),
        ),
        migrations.AddIndex(
            model_name='postkeywordhit',
            index=models.Index(fields=['post', 'topic'], name='posts_postk_post_id_09c611_idx'),
        ),
        migrations.AddIndex(
            model_name='postkeywordhit',
            index=models.Index(fields=['keyword'], name='posts_postk_keyword_d35fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='postsnapshot',
            index=models.Index(fields=['post', 'collected_at'], name='posts_posts_post_id_57ea44_idx'),
        ),
        migrations.AddIndex(
            model_name='posttopichit',
            index=models.Index(fields=['topic', 'first_hit_at'], name='posts_postt_topic_i_057e16_idx'),
        ),
        migrations.AddConstraint(
            model_name='posttopichit',
            constraint=models.UniqueConstraint(fields=('post', 'topic'), name='uq_post_topic'),
        ),
    ]
