# Generated by Django 6.0.8 on 2026-08-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('platform', 'post_id'), name='uq_post_platform_pid'),
        ),
        migrations.AddConstraint(
            model_name='postkeywordhit',
            constraint=models.UniqueConstraint(fields=('post', 'topic', 'keyword'), name='uq_post_topic_keyword'),
        ),
    ]
