# Generated by Django 6.0.8 on 2026-08-15 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0003_alter_topic_collection_interval"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicKeywordsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "window",
                    models.CharField(
                        default="7d", max_length=16, verbose_name="时间窗口"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(blank=True, default=list, verbose_name="关键词"),
                ),
                (
                    "computed_at",
                    models.DateTimeField(auto_now=True, verbose_name="计算时间"),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keyword_snapshots",
                        to="topics.topic",
                        verbose_name="主题",
                    ),
                ),
            ],
            options={
                "verbose_name": "关键词快照",
                "verbose_name_plural": "关键词快照",
            },
        ),
    ]
