# Generated by Django 6.0.8 on 2026-08-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('negative_keyword', '负面关键词出现'), ('like_threshold', '负面帖点赞超阈值'), ('negative_spike', '负面帖数量激增'), ('coordinated_posting', '同观点多账号集中发布'), ('interaction_spike', '互动量异常增长'), ('key_author_negative', '重点账号发布负面')], max_length=32, verbose_name='规则类型')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置参数')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=8, verbose_name='关注等级')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('notify_channels', models.JSONField(blank=True, default=list, verbose_name='通知渠道')),
                ('notify_recipients', models.JSONField(blank=True, default=list, verbose_name='通知对象')),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='同规则触发防抖', verbose_name='冷却时间(分钟)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '预警规则',
                'verbose_name_plural': '预警规则',
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('level', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], max_length=8, verbose_name='关注等级')),
                ('reason', models.TextField(verbose_name='触发原因')),
                ('matched_posts', models.JSONField(blank=True, default=list, verbose_name='相关帖子')),
                ('matched_keywords', models.JSONField(blank=True, default=list, verbose_name='命中关键词')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='指标快照')),
                ('status', models.CharField(choices=[('new', '待处理'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='new', max_length=16, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_alert_events', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='topics.topic', verbose_name='主题')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '预警事件',
                'verbose_name_plural': '预警事件',
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('platform', '站内消息'), ('email', '邮件')], max_length=16, verbose_name='渠道')),
                ('recipient', models.CharField(max_length=128, verbose_name='接收方')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alertevent', verbose_name='事件')),
            ],
            options={
                'verbose_name': '通知记录',
                'verbose_name_plural': '通知记录',
                'indexes': [models.Index(fields=['status', 'created_at'], name='alerts_aler_status_5abf54_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['topic', 'enabled'], name='alerts_aler_topic_i_ce98ec_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['topic', 'triggered_at'], name='alerts_aler_topic_i_2ec21d_idx'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['status', 'triggered_at'], name='alerts_aler_status_449110_idx'),
        ),
    ]
