# Generated by Django 6.0.8 on 2026-08-14 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_post_uq_post_platform_pid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=16, verbose_name='平台')),
                ('platform_post_id', models.CharField(max_length=128, verbose_name='平台侧帖子ID')),
                ('comment_id', models.CharField(max_length=128, verbose_name='平台侧评论ID')),
                ('author_name', models.CharField(blank=True, default='', max_length=128, verbose_name='评论作者')),
                ('content', models.TextField(blank=True, default='', verbose_name='评论内容')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='点赞数')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawled_comments', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '平台评论',
                'verbose_name_plural': '平台评论',
                'indexes': [models.Index(fields=['platform', 'platform_post_id'], name='plugins_pos_platfor_0d7ad4_idx'), models.Index(fields=['post'], name='plugins_pos_post_id_5c93a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'comment_id'), name='uq_plugin_comment_platform_cid')],
            },
        ),
    ]
