# Generated by Django 6.0.8 on 2026-08-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCrawlerFileState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512, unique=True, verbose_name='文件相对路径')),
                ('imported_lines', models.IntegerField(default=0, verbose_name='已导入行数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'MediaCrawler 导入进度',
                'verbose_name_plural': 'MediaCrawler 导入进度',
            },
        ),
        migrations.CreateModel(
            name='MediaCrawlerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='xhs', max_length=16, verbose_name='平台')),
                ('keywords', models.TextField(blank=True, default='', verbose_name='关键词')),
                ('status', models.CharField(choices=[('running', '运行中'), ('finished', '已完成'), ('importing', '导入中'), ('failed', '失败'), ('stopped', '已停止')], default='running', max_length=16, verbose_name='状态')),
                ('log_path', models.CharField(blank=True, default='', max_length=512, verbose_name='日志文件')),
                ('pid', models.IntegerField(blank=True, null=True, verbose_name='进程号')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('fetched_count', models.IntegerField(default=0, verbose_name='抓取条数')),
                ('new_count', models.IntegerField(default=0, verbose_name='新增条数')),
                ('duplicate_count', models.IntegerField(default=0, verbose_name='重复条数')),
                ('updated_count', models.IntegerField(default=0, verbose_name='更新条数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='导入评论数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediacrawler_runs', to='topics.topic', verbose_name='关联主题')),
            ],
            options={
                'verbose_name': 'MediaCrawler 运行记录',
                'verbose_name_plural': 'MediaCrawler 运行记录',
                'ordering': ['-id'],
            },
        ),
    ]
