# Generated by Django 6.0.8 on 2026-08-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_mediacrawlerfilestate_mediacrawlerrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacrawlerrun',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('queued', '排队中'), ('finished', '已完成'), ('importing', '导入中'), ('failed', '失败'), ('stopped', '已停止')], default='running', max_length=16, verbose_name='状态'),
        ),
    ]
