# Generated by Django 6.0.8 on 2026-08-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0003_alter_mediacrawlerrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediacrawlerrun",
            name="snapshot_lines",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="任务启动时各数据文件的行数快照；导入时只处理快照之后本任务新增的行，保证「任务爬到的帖子都属于该任务主题」",
                verbose_name="数据文件行数快照",
            ),
        ),
    ]
