# Generated by Django 6.0.8 on 2026-08-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='主题名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('platforms', models.JSONField(blank=True, default=list, verbose_name='采集平台')),
                ('collection_interval', models.IntegerField(default=30, help_text='10~1440 分钟', verbose_name='采集频率(分钟)')),
                ('monitor_start', models.DateTimeField(blank=True, null=True, verbose_name='监测开始时间')),
                ('monitor_end', models.DateTimeField(blank=True, null=True, verbose_name='监测结束时间')),
                ('status', models.CharField(choices=[('active', '监测中'), ('paused', '已暂停'), ('archived', '已归档'), ('deleted', '已删除')], default='active', max_length=16, verbose_name='状态')),
                ('priority', models.IntegerField(default=5, help_text='1(最高)~10(最低)', verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '舆情主题',
                'verbose_name_plural': '舆情主题',
            },
        ),
        migrations.CreateModel(
            name='TopicExclusionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('xiaohongshu', '小红书'), ('weibo', '微博'), ('mock', '模拟数据')], max_length=16, verbose_name='平台')),
                ('author_name', models.CharField(max_length=128, verbose_name='作者名')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_users', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '排除用户',
                'verbose_name_plural': '排除用户',
            },
        ),
        migrations.CreateModel(
            name='TopicKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, verbose_name='关键词')),
                ('kind', models.CharField(choices=[('core', '核心关键词'), ('related', '关联关键词'), ('exclude', '排除关键词')], default='core', max_length=8, verbose_name='类型')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '主题关键词',
                'verbose_name_plural': '主题关键词',
            },
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status', 'priority'], name='topics_topi_status_3113d1_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['name'], name='topics_topi_name_0394c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicexclusionuser',
            constraint=models.UniqueConstraint(fields=('topic', 'platform', 'author_name'), name='uq_topic_platform_author'),
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['word'], name='topics_topi_word_f367f3_idx'),
        ),
        migrations.AddIndex(
            model_name='topickeyword',
            index=models.Index(fields=['topic'], name='topics_topi_topic_i_595f1e_idx'),
        ),
    ]
