# Generated by Django 6.0.8 on 2026-08-14 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='topic',
            name='topics_topi_status_3113d1_idx',
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['status'], name='topics_topi_status_54d68a_idx'),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='priority',
        ),
    ]
