# Generated by Django 6.0.8 on 2026-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topics", "0002_remove_topic_topics_topi_status_3113d1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="collection_interval",
            field=models.IntegerField(
                default=30, help_text="5~1440 分钟", verbose_name="采集频率(分钟)"
            ),
        ),
    ]
