# Generated by Django 6.0.8 on 2026-08-05 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=16, verbose_name='平台')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('canceled', '已取消')], default='pending', max_length=16, verbose_name='状态')),
                ('priority', models.IntegerField(default=5, verbose_name='优先级')),
                ('trigger_type', models.CharField(choices=[('schedule', '定时'), ('manual', '手动')], default='schedule', max_length=16, verbose_name='触发方式')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('fetched_count', models.IntegerField(default=0, verbose_name='采集条数')),
                ('new_count', models.IntegerField(default=0, verbose_name='新增条数')),
                ('updated_count', models.IntegerField(default=0, verbose_name='更新条数')),
                ('duplicate_count', models.IntegerField(default=0, verbose_name='重复条数')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('cursor', models.CharField(blank=True, max_length=256, null=True, verbose_name='增量游标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '采集运行记录',
                'verbose_name_plural': '采集运行记录',
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='tasks_colle_status_c4ff16_idx'), models.Index(fields=['topic', 'status', 'created_at'], name='tasks_colle_topic_i_2f6422_idx')],
            },
        ),
    ]
