# Generated by Django 6.0.8 on 2026-08-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('topics', '0002_remove_topic_topics_topi_status_3113d1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collectionrun',
            name='tasks_colle_status_c4ff16_idx',
        ),
        migrations.AddIndex(
            model_name='collectionrun',
            index=models.Index(fields=['status', 'created_at'], name='tasks_colle_status_49f743_idx'),
        ),
        migrations.RemoveField(
            model_name='collectionrun',
            name='priority',
        ),
    ]
