# Generated by Django 6.0.8 on 2026-08-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('post', '帖子数据'), ('full', '全量数据')], default='post', max_length=16, verbose_name='导出类型')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='筛选条件')),
                ('file_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='文件路径')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '处理中'), ('done', '完成'), ('failed', '失败')], default='pending', max_length=16, verbose_name='状态')),
                ('row_count', models.IntegerField(default=0, verbose_name='导出行数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exports', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '数据导出任务',
                'verbose_name_plural': '数据导出任务',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报')], max_length=8, verbose_name='周期类型')),
                ('report_date', models.DateField(verbose_name='报告日期')),
                ('title', models.CharField(max_length=256, verbose_name='标题')),
                ('summary', models.TextField(blank=True, default='', verbose_name='摘要')),
                ('statistics', models.JSONField(blank=True, default=dict, verbose_name='统计信息')),
                ('chart_image', models.CharField(blank=True, max_length=256, null=True, verbose_name='图表文件')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('done', '已完成'), ('failed', '失败')], default='generating', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '舆情报告',
                'verbose_name_plural': '舆情报告',
                'constraints': [models.UniqueConstraint(fields=('topic', 'period_type', 'report_date'), name='uq_topic_period_date')],
            },
        ),
    ]
