# Generated by Django 6.0.8 on 2026-08-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="report",
            name="uq_topic_period_date",
        ),
    ]
