# Generated by Django 6.0.8 on 2026-08-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('topics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_score', models.FloatField(default=0, verbose_name='相关度')),
                ('is_related', models.BooleanField(default=False, verbose_name='是否相关')),
                ('sentiment', models.CharField(choices=[('positive', '正面'), ('neutral', '中性'), ('unknown', '未知'), ('negative', '负面')], default='unknown', max_length=16, verbose_name='情感')),
                ('sentiment_score', models.FloatField(default=0, verbose_name='情感得分')),
                ('sentiment_source', models.CharField(choices=[('rule', '规则'), ('llm', '大模型'), ('manual', '人工修正')], default='llm', max_length=8, verbose_name='情感来源')),
                ('key_viewpoints', models.JSONField(blank=True, default=list, verbose_name='核心观点')),
                ('key_entities', models.JSONField(blank=True, default=list, verbose_name='关键实体')),
                ('high_freq_keywords', models.JSONField(blank=True, default=list, verbose_name='高频关键词')),
                ('heat_score', models.FloatField(default=0, verbose_name='热度分')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='posts.post', verbose_name='帖子')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '帖子分析结果',
                'verbose_name_plural': '帖子分析结果',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='实体名')),
                ('type', models.CharField(choices=[('brand', '品牌'), ('drama', '剧集'), ('variety', '综艺'), ('actor', '艺人'), ('character', '角色'), ('tag', '话题')], max_length=16, verbose_name='类型')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='别名')),
                ('mention_count', models.IntegerField(default=0, verbose_name='提及次数')),
            ],
            options={
                'verbose_name': '实体',
                'verbose_name_plural': '实体',
                'constraints': [models.UniqueConstraint(fields=('name', 'type'), name='uq_entity_name_type')],
            },
        ),
        migrations.CreateModel(
            name='ManualCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('sentiment', '情感倾向'), ('related', '相关性'), ('viewpoint', '核心观点'), ('entities', '关键实体')], max_length=16, verbose_name='修正字段')),
                ('original_value', models.TextField(verbose_name='原始值')),
                ('corrected_value', models.TextField(verbose_name='修正值')),
                ('note', models.TextField(blank=True, default='', verbose_name='修正说明')),
                ('corrected_at', models.DateTimeField(auto_now_add=True, verbose_name='修正时间')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.analysisresult', verbose_name='分析结果')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to=settings.AUTH_USER_MODEL, verbose_name='修正人')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '人工修正记录',
                'verbose_name_plural': '人工修正记录',
            },
        ),
        migrations.CreateModel(
            name='PostEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(max_length=128, verbose_name='原文提及')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='analysis.entity', verbose_name='实体')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='posts.post', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '帖子实体',
                'verbose_name_plural': '帖子实体',
            },
        ),
        migrations.CreateModel(
            name='ThemeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('custom', '自定义')], max_length=8, verbose_name='周期类型')),
                ('period_start', models.DateField(verbose_name='周期开始')),
                ('period_end', models.DateField(verbose_name='周期结束')),
                ('summary_text', models.TextField(blank=True, default='', verbose_name='摘要文本')),
                ('statistics', models.JSONField(blank=True, default=dict, verbose_name='统计信息')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '阶段摘要',
                'verbose_name_plural': '阶段摘要',
            },
        ),
        migrations.CreateModel(
            name='ViewpointCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128, verbose_name='聚类标签')),
                ('post_count', models.IntegerField(default=0, verbose_name='帖子数')),
                ('sentiment_distribution', models.JSONField(blank=True, default=dict, verbose_name='情感分布')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpoint_clusters', to='topics.topic', verbose_name='主题')),
            ],
            options={
                'verbose_name': '观点聚类',
                'verbose_name_plural': '观点聚类',
            },
        ),
        migrations.CreateModel(
            name='Viewpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='观点文本')),
                ('sentiment', models.CharField(choices=[('positive', '正面'), ('neutral', '中性'), ('unknown', '未知'), ('negative', '负面')], default='neutral', max_length=16, verbose_name='情感')),
                ('mention_count', models.IntegerField(default=0, verbose_name='提及次数')),
                ('representative_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.post', verbose_name='代表帖子')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewpoints', to='topics.topic', verbose_name='主题')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewpoints', to='analysis.viewpointcluster', verbose_name='聚类')),
            ],
            options={
                'verbose_name': '观点',
                'verbose_name_plural': '观点',
            },
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['topic', 'sentiment'], name='analysis_an_topic_i_405e06_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['topic', 'is_related'], name='analysis_an_topic_i_25d706_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['topic', 'heat_score'], name='analysis_an_topic_i_1825d3_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['post'], name='analysis_an_post_id_147c5e_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcorrection',
            index=models.Index(fields=['post'], name='analysis_ma_post_id_d66d64_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['entity'], name='analysis_po_entity__0e629b_idx'),
        ),
        migrations.AddIndex(
            model_name='postentity',
            index=models.Index(fields=['post'], name='analysis_po_post_id_af5f4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='themesummary',
            constraint=models.UniqueConstraint(fields=('topic', 'period_type', 'period_start', 'period_end'), name='uq_topic_period'),
        ),
        migrations.AddIndex(
            model_name='viewpointcluster',
            index=models.Index(fields=['topic'], name='analysis_vi_topic_i_b752e9_idx'),
        ),
        migrations.AddIndex(
            model_name='viewpoint',
            index=models.Index(fields=['topic', 'mention_count'], name='analysis_vi_topic_i_fa3ed0_idx'),
        ),
    ]
